# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bf7cabc7eaeb9b5140fd2a9ad276c22030ca7d7c2713740f53eb2726f45e39f04f83248c81f98d048085392d35f72058456ef0c6eaaeb66ee083ac15418a0c1

test:
  secret_key_base: b0cbec0f499f8781fd371b582bc188c6179d2cdc8697e661a6d5f8b04b080fdea29b1032dc8b5d98e325dbbb24c97c0937d480866d560d0d1c6cba098b92e1f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
